### ISSUE TITLE
Add shutdown logic

### ISSUE THREAD

**Issue by zuck** [nbalduzzi/fastify-knexjs#2]
It would be useful to register a hook to catch the 'close' event of Fastify and close existing connections to DB:

```
fastify.addHook('onClose', (instance, done) => {
  instance.knex.destroy()
  done()
})
```

**Comment by nbalduzzi** [comment]
Hi @zuck, feel free to do a PR with tests! ;)

**Comment by zuck** [comment]
Hi @nbalduzzi , any chance to see #5 or #7 merged in order to fix this issue?

**Comment by nbalduzzi** [comment]
Shutdown logic adde to v1.2.0
